/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package us.physion.ovation.ui.browser.insertion;

import java.util.HashMap;
import java.util.Map;
import javax.swing.ListSelectionModel;
import org.openide.util.ChangeSupport;
import us.physion.ovation.ui.interfaces.ParameterTableModel;

/**
 *
 * @author jackie
 */
public class KeyValuePanel extends javax.swing.JPanel {

    private ChangeSupport cs;
    private ParameterTableModel paramModel;
    private String name;
    private String description;
    
    @Override
    public String getName() {
        return name;
    }
    
    /**
     * Creates new form KeyValuePanel
     */
    public KeyValuePanel(ChangeSupport cs, String name, String description) {
        this.cs = cs;
        this.name = name;
        this.description = description;
        paramModel = new ParameterTableModel(true);
        initComponents();
        label.setText(description);
    }
    
    public void setParameters(Map<String, Object> params)
    {
        if (params == null)
            params = new HashMap();
        paramModel.setParams(params);
    }
    
    public Map<String, Object> getParameters()
    {
        return paramModel.getParams();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        parameterTable = new javax.swing.JTable();

        label.setText(org.openide.util.NbBundle.getMessage(KeyValuePanel.class, "KeyValuePanel.label.text")); // NOI18N

        parameterTable.setModel(paramModel);
        jScrollPane1.setViewportView(parameterTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .add(label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable parameterTable;
    // End of variables declaration//GEN-END:variables
}
