/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package us.physion.ovation.ui.detailviews;

import java.util.*;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import us.physion.ovation.DataContext;
import us.physion.ovation.ui.*;
import us.physion.ovation.ui.interfaces.ConnectionProvider;
import us.physion.ovation.ui.interfaces.EventQueueUtilities;
import us.physion.ovation.ui.interfaces.IEntityWrapper;


/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//us.physion.ovation.detailviews//PropertiesView//EN",
autostore = false)
@TopComponent.Description(preferredID = "PropertiesViewTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "properties", openAtStartup = true)
@ActionID(category = "Window", id = "us.physion.ovation.detailviews.PropertiesViewTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_PropertiesViewAction",
preferredID = "PropertiesViewTopComponent")
@Messages({
    "CTL_PropertiesViewAction=Properties",
    "CTL_PropertiesViewTopComponent=Properties",
    "HINT_PropertiesViewTopComponent=Displays the properties of the selected entites"
})
public final class PropertiesViewTopComponent extends TopComponent {

    Lookup.Result global;
    private Collection<? extends IEntityWrapper> entities;
    private final LookupListener listener = (LookupEvent le) -> {
        //TODO: we should have some other Interface for things that can update the tags view
        //then we could get rid of the Library dependancy on the Explorer API
        if (TopComponent.getRegistry().getActivated() instanceof ExplorerManager.Provider)
        {
            update();
        }
    };

    public void update()
    {
        EventQueueUtilities.runOffEDT(() -> {
            update(global.allInstances());
        });
    }

    public us.physion.ovation.ui.ScrollableTableTree getTableTree()
    {
        return (us.physion.ovation.ui.ScrollableTableTree)tableTree;
    }

    protected void setTableTree(us.physion.ovation.ui.ScrollableTableTree t)
    {
        tableTree = t;
    }

    public void update(final Collection<? extends IEntityWrapper> entities)
    {
        DataContext c = Lookup.getDefault().lookup(ConnectionProvider.class).getDefaultContext();
        setEntities(entities, c);

        if (entities.size() > 1) {
            EventQueueUtilities.runOnEDT(() -> {
                setName(Bundle.CTL_PropertiesViewTopComponent() + " - " + entities.size() + " entities");
            });
        } else {
            EventQueueUtilities.runOnEDT(() -> {
                setName(Bundle.CTL_PropertiesViewTopComponent());
            });
        }
    }

    protected List<TableTreeKey> setEntities(Collection<? extends IEntityWrapper> entities, DataContext c)
    {
        List<TableTreeKey> properties = PerUserAnnotationSets.createPropertySets(entities, c);
        ((ScrollableTableTree) tableTree).setKeys(properties);

        this.entities = entities;
        return properties;
    }

    public PropertiesViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_PropertiesViewTopComponent());
        setToolTipText(Bundle.HINT_PropertiesViewTopComponent());

        global = Utilities.actionsGlobalContext().lookupResult(IEntityWrapper.class);
        global.addLookupListener(listener);
    }

    public Collection<? extends IEntityWrapper> getEntities()
    {
        return entities;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableTree = new us.physion.ovation.ui.ScrollableTableTree();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableTree, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableTree, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane tableTree;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
