/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package us.physion.ovation.ui.detailviews;

import java.awt.event.KeyEvent;
import java.util.Locale;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

/**
 *
 * @author huecotanks
 */
public class NotesPanel extends javax.swing.JPanel {

    String text;
    DateTime timestamp;
    /**
     * Creates new form NotesPanel
     */
    public NotesPanel(NoteValue n) {
        this();
        setNoteValue(n);

    }
    
    public NotesPanel() {
        initComponents();
        jTextArea1.setEditable(false);
    }
    
    public void setNoteValue(NoteValue n)
    {
        text = n.text;
        timestamp = n.timestamp;
        
        if (timestamp != null) {
            DateTimeFormatter dtf = DateTimeFormat.forStyle("SM").withLocale(Locale.getDefault());
            dateText.setText(n.timestamp.toString(dtf));
        }
        jTextArea1.setText(text);
        jScrollPane1.setSize(jScrollPane1.getPreferredSize());
    }
    
    public void resize()
    {
        jScrollPane1.setSize(jScrollPane1.getPreferredSize());
    }
    
    void setEditable(boolean b)
    {
       jTextArea1.setEditable(b);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        dateText.setText(org.openide.util.NbBundle.getMessage(NotesPanel.class, "NotesPanel.dateText.text")); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(dateText)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(dateText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        text = jTextArea1.getText();

        if (evt.getKeyCode() == KeyEvent.VK_ENTER)//enter key
        {
            this.firePropertyChange("done.editing", true, false);
        }
        
    }//GEN-LAST:event_jTextArea1KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
